apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebro-test
spec:
  selector:
    matchLabels:
      app: cerebro-test
  replicas: 1
  template:
    metadata:
      labels:
        app: cerebro-test
    spec:
      nodeName: node0.mop-redo-2.orion-pg0.utah.cloudlab.us
      containers:
      - name: cerebro-main
        image: prsridha/cerebro-base:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - name: cerebro-repo
          mountPath: /cerebro-repo
        - name: user-repo
          mountPath: /user-repo
      initContainers:
      - name: git-sync-cerebro
        image: prsridha/git-sync
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: cerebro-repo
          mountPath: /cerebro-repo
        - name: git-secret
          mountPath: /etc/git-secret
        env:
        - name: GIT_SYNC_REPO
          value: git@github.com:prsridha/cerebro-kube.git
        - name: GIT_SYNC_BRANCH
          value: main
        - name: GIT_SYNC_ROOT
          value: /cerebro-repo
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_SERVER
          value: github.com
        securityContext:
          runAsUser: 0
      - name: git-sync-user-repo
        image: prsridha/git-sync
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: user-repo
          mountPath: /user-repo
        - name: git-secret
          mountPath: /etc/git-secret
        env:
        - name: GIT_SYNC_REPO
          value: git@github.com:prsridha/coco-mop.git
        - name: GIT_SYNC_BRANCH
          value: main
        - name: GIT_SYNC_ROOT
          value: /user-repo
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_SERVER
          value: github.com
        securityContext:
          runAsUser: 0
      volumes:
      - name: cerebro-repo
        hostPath:
          path: /users/prsridha/cerebro-repo
          type: Directory
      - name: user-repo
        hostPath:
          path: /users/prsridha/user-repo
          type: Directory
      - name: git-secret
        secret:
          defaultMode: 256
          secretName: git-creds # your-ssh-key