# Worker Service 
apiVersion: v1
kind: Service
metadata:
  name: workeretlsvc{{ .Values.workerID }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: cerebro-worker-etl
spec:
  selector:
    app: cerebro-worker-etl-{{ .Values.workerID }}
  ports:
  - name: "rpc-port"
    protocol: "TCP"
    port: {{ .Values.workerETL.rpcPort }}
    targetPort: {{ .Values.workerETL.rpcPort }}
  type: ClusterIP