controller:
  volumes:
    configCapacity: 500Mi
    configMountPath: /data/cerebro_config_storage
    checkpointCapacity: 20Gi
    checkpointMountPath: /data/cerebro_checkpoint_storage
    metricsCapacity: 5Gi
    metricsMountPath: /data/cerebro_metrics_storage
    dataCapacity: 50Gi
    dataMountPath: /data/cerebro_data_storage
    cerebroRepoHostPath: /home/ec2-user/cerebro-repo
    cerebroRepoMountPath: /cerebro-repo
    userRepoHostPath: /home/ec2-user/user-repo
    userRepoMountPath: /user-repo
  git:
    cerebroRepoURL: git@github.com:prsridha/cerebro-kube.git
    cerebroRepoBranch: feature/aws-gpu
    userRepoURL: git@github.com:prsridha/coco-mop.git
    userRepoBranch: feature/aws-gpu
    gitSyncImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/git-sync:latest
    image: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  services:
    daskDashboardPort: 8787
    daskPort: 8786
    tensorboardPort: 6006
    jupyterPort: 8888
    jupyterUserPort: 9999
creds:
  gitServer: github.com
  gitToken: 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
namespace: cerebro
cluster:
  name: cerebro-kube-sm-1
  workerSpot: true
  workers: 4
  region: ca-central-1
  controllerInstance: t3.xlarge
  workerInstance: g4dn.4xlarge
  volumeSize: 200
  efsFileSystemIds:
    checkpointFsId: fs-04957597bb9603c68
    dataFsId: fs-07c0f3216a14aeaf1
    metricsFsId: fs-0068cbb83059a6285
    configFsId: fs-0ff4d5c931078c7bf
  pemPath: /Users/pradsrid/Mine/Masters/Research/Cerebro/AWSCreds/cerebro-kube-kp.pem
  containerImageRegistery: 602401143452.dkr.ecr.ap-south-1.amazonaws.com
  nodeLocalListenIP: 169.254.0.0
workerETL:
  workerDataPath: /cerebro_data_storage_worker
  port: 8787
  schedulerIP: 10.100.109.225
  percentETLCores: 75
  workerContainerPort: 8787
  workerImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
workerMOP:
  dataMountPath: /data/cerebro_data_storage
  workerDataPath: /cerebro_data_storage_worker
  rcpport: 7777
  workerImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
