controller:
  volumes:
    configCapacity: 1Gi
    configMountPath: /data/cerebro_config_storage
    checkpointCapacity: 20Gi
    checkpointMountPath: /data/cerebro_checkpoint_storage
    metricsCapacity: 5Gi
    metricsMountPath: /data/cerebro_metrics_storage
    dataCapacity: 70Gi
    dataMountPath: /data/cerebro_data_storage
    cerebroRepoHostPath: /home/ec2-user/cerebro-repo
    cerebroRepoMountPath: /cerebro-repo
    userRepoHostPath: /home/ec2-user/user-repo
    userRepoMountPath: /user-repo
  git:
    cerebroRepoURL: git@github.com:prsridha/cerebro-kube.git
    cerebroRepoBranch: feature/multi-gpu-mop
    userRepoURL: git@github.com:prsridha/coco-mop.git
    userRepoBranch: feature/multi-gpu-mop
    gitSyncImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/git-sync:latest
    image: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  services:
    daskDashboardPort: 8787
    daskPort: 8786
    tensorboardPort: 6006
    jupyterPort: 8888
    jupyterUserPort: 9999
creds:
  gitServer: github.com
  gitToken: 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
namespace: cerebro
cluster:
  name: cerebro-kube-small-2
  workerSpot: true
  workers: 4
  region: ca-central-1
  controllerInstance: t3.2xlarge
  workerInstance:
  - g5.12xlarge
  - g3.16xlarge
  - g4dn.12xlarge
  volumeSize: 200
  efsFileSystemIds:
    checkpointFsId: fs-0a806ec459f2fdf31
    dataFsId: fs-0a07df687561df20e
    metricsFsId: fs-06d428a3e231bc7a4
    configFsId: fs-099d427df80784ce4
  pemPath: /Users/pradsrid/Mine/Masters/Research/Cerebro/AWSCreds/cerebro-kube-kp.pem
  containerImageRegistery: 602401143452.dkr.ecr.ap-south-1.amazonaws.com
  nodeLocalListenIP: 169.254.0.0
workerETL:
  workerDataPath: /cerebro_data_storage_worker
  port: 8787
  schedulerIP: 10.100.38.166
  percentETLCores: 100
  workerContainerPort: 8787
  workerImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
workerMOP:
  dataMountPath: /data/cerebro_data_storage
  workerDataPath: /cerebro_data_storage_worker
  rcpport: 7777
  workerImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
