creds:
  dockerToken: b9cdaf75-996d-48b1-be51-a0bfba41d59f
  dockerUser: prsridha
  gitServer: github.com
  gitToken: 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
controller:
  cerebroRepoHostPath: /users/prsridha/cerebro-repo
  cerebroRepoMountPath: /cerebro-repo
  cerebroRepoURL: git@github.com:prsridha/cerebro-kube.git
  checkpointCapacity: 5Gi
  checkpointHostPath: /cerebro-checkpoint
  checkpointMountPath: /data/cerebro_checkpoint_storage
  configCapacity: 100Mi
  configHostPath: /cerebro-config
  configMountPath: /data/cerebro_config_storage
  containerPort: 8786
  dataCapacity: 50Gi
  dataHostPath: /cerebro-data
  dataMountPath: /data/cerebro_data_storage
  gitSyncImage: prsridha/git-sync
  hyperparameterMountPath: /data/hyperparameter_properties
  image: prsridha/cerebro-base:latest
  port: 8786
  propertiesMountPath: /data/cerebro_properties
  userRepoHostPath: /users/prsridha/user-repo
  userRepoMountPath: /user-repo
  userRepoURL: git@github.com:prsridha/coco-mop.git
namespace: cerebro
nfs:
  capacity: 50Gi
  ip: 10.101.70.83
worker:
  checkpointMountPath: /data/cerebro_checkpoint_storage
  controllerDataHostPath: /cerebro-data
  controllerDataMountPath: /data/cerebro_data_storage
  dataCapacity: 10Gi
  dataMountPath: /data/cerebro_data_storage_worker
  hyperparameterMountPath: /data/hyperparameter_properties
  port: 8787
  rcpport: 7777
  workerContainerPort: 8787
  workerImage: prsridha/cerebro-kube:latest
