controller:
  volumes:
    configCapacity: 1Gi
    configMountPath: /data/cerebro_config_storage
    nodeHardwareInfo: /data/node_hardware_info
    checkpointCapacity: 20Gi
    checkpointMountPath: /data/cerebro_checkpoint_storage
    metricsCapacity: 5Gi
    metricsMountPath: /data/cerebro_metrics_storage
    dataCapacity: 70Gi
    dataMountPath: /data/cerebro_data_storage
    cerebroRepoHostPath: /home/ec2-user/cerebro-repo
    cerebroRepoMountPath: /cerebro-repo
    userRepoHostPath: /home/ec2-user/user-repo
    userRepoMountPath: /user-repo
    webappRepoHostPath: /home/ec2-user/web-app
    webappMountPath: /webapp
  git:
    cerebroRepoURL: git@github.com:prsridha/cerebro-kube.git
    cerebroRepoBranch: demo
    userRepoURL: git@github.com:prsridha/coco-mop.git
    userRepoBranch: demo
    gitSyncImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/git-sync:latest
    image: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  services:
    daskPort: 8786
    webappPort: 8080
    webappUIPort: 80
    jupyterPort: 8888
    jupyterNodePort: 38888
    tensorboardNodePort: 39999
    webappNodePort: 308080
    webappUINodePort: 30080
creds:
  gitServer: github.com
  gitToken: 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
namespace: cerebro
cluster:
  name: cerebro-kube-small-1
  workerSpotInstance: false
  numWorkers: 4
  region: ca-central-1
  controllerInstance: t3.2xlarge
  workerInstances:
  - g4dn.12xlarge
  volumeSize: 200
  efsFileSystemIds:
    checkpointFsId: fs-0a36acc3c390eaa1c
    dataFsId: fs-0ab4519ba75bafeea
    metricsFsId: fs-07e7c393469837d10
    configFsId: fs-0528cdb1832382ac3
  pemPath: /Users/pradsrid/Mine/Masters/Research/Cerebro/AWSCreds/cerebro-kube-kp.pem
  containerImageRegistery: 602401143452.dkr.ecr.ap-south-1.amazonaws.com
  networking:
    nodeLocalListenIP: 169.254.0.0
    prometheusNodePort: 30090
workerETL:
  workerDataPath: /cerebro_data_storage_worker
  port: 8787
  percentETLCores: 50
  workerContainerPort: 8787
  workerImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
workerMOP:
  dataMountPath: /data/cerebro_data_storage
  workerDataPath: /cerebro_data_storage_worker
  rpcport: 7777
  workerImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
