controller:
  volumes:
    configCapacity: 1Gi
    configMountPath: /data/cerebro_config_storage
    nodeHardwareInfo: /data/node_hardware_info
    checkpointCapacity: 20Gi
    checkpointMountPath: /data/cerebro_checkpoint_storage
    metricsCapacity: 5Gi
    metricsMountPath: /data/cerebro_metrics_storage
    dataCapacity: 70Gi
    dataMountPath: /data/cerebro_data_storage
    cerebroRepoHostPath: /home/ec2-user/cerebro-repo
    cerebroRepoMountPath: /cerebro-repo
    userRepoHostPath: /home/ec2-user/user-repo
    userRepoMountPath: /user-repo
  git:
    cerebroRepoURL: git@github.com:prsridha/cerebro-kube.git
    cerebroRepoBranch: demo
    gitSyncImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/git-sync:latest
    image: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  services:
    jupyterPort: 8888
    jupyterNodePort: 30888
    tensorboardPort: 6006
    tensorboardNodePort: 30999
creds:
  gitServer: github.com
  gitToken: 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
  jupyterTokenSting: projectcerebro
namespace: cerebro
cluster:
  name: cerebro-kube-tiny
  workerSpotInstance: false
  numWorkers: 3
  region: ca-central-1
  controllerInstance: t3.2xlarge
  workerInstances:
  - g4dn.12xlarge
  volumeSize: 200
  efsFileSystemId: fs-0f70377aaf0311f30
  pemPath: /Users/pradsrid/Mine/Masters/Research/Cerebro/AWSCreds/cerebro-kube-kp.pem
  containerImageRegistery: 602401143452.dkr.ecr.ap-south-1.amazonaws.com
  networking:
    nodeLocalListenIP: 169.254.0.0
    prometheusNodePort: 30090
    grafanaNodePort: 30030
    lokiPort: 3100
    publicDNSName: ec2-3-99-180-77.ca-central-1.compute.amazonaws.com
workerETL:
  workerDataPath: /cerebro_data_storage_worker
  rpcPort: 7777
  workerImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
workerMOP:
  dataMountPath: /data/cerebro_data_storage
  workerDataPath: /cerebro_data_storage_worker
  rpcPort: 7777
  workerImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
webApp:
  hostPath: /home/ec2-user/web-app
  mountPath: /webapp
  backendPort: 8083
  backendNodePort: 30083
  uiPort: 80
  uiNodePort: 30080
  repoURL: git@github.com:prsridha/cerebro-ui.git
  image: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-ui:latest
