controller:
  volumes:
    configCapacity: 500Mi
    configMountPath: /data/cerebro_config_storage
    checkpointCapacity: 20Gi
    checkpointMountPath: /data/cerebro_checkpoint_storage
    metricsCapacity: 5Gi
    metricsMountPath: /data/cerebro_metrics_storage
    dataCapacity: 50Gi
    dataMountPath: /data/cerebro_data_storage
    cerebroRepoHostPath: /home/ec2-user/cerebro-repo
    cerebroRepoMountPath: /cerebro-repo
    userRepoHostPath: /home/ec2-user/user-repo
    userRepoMountPath: /user-repo
  git:
    cerebroRepoURL: git@github.com:prsridha/cerebro-kube.git
    cerebroRepoBranch: main
    userRepoURL: git@github.com:prsridha/coco-mop.git
    gitSyncImage: prsridha/git-sync
    image: prsridha/cerebro-base:latest
  services:
    daskDashboardPort: 8787
    daskPort: 8786
    tensorboardPort: 6006
    jupyterPort: 8888
    jupyterUserPort: 9999
creds:
  dockerToken: b9cdaf75-996d-48b1-be51-a0bfba41d59f
  dockerUser: prsridha
  gitServer: github.com
  gitToken: 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
namespace: cerebro
cluster:
  name: cerebro-kube-2
  workers: 4
  region: ap-south-1
  controllerInstance: t3.medium
  workerInstance: t3.large
  volumeSize: 80
  efsFileSystemID: fs-09534e0c115192742
  pemPath: /Users/pradsrid/Mine/Masters/Research/Cerebro/AWSCreds/cerebro-kube-kp.pem
workerETL:
  checkpointPath: /data/cerebro_checkpoint_storage
  controllerDataPath: /data/cerebro_data_storage
  workerDataPath: /cerebro_data_storage_worker
  nworkers: 16
  port: 8787
  schedulerIP: 10.97.81.73
  workerContainerPort: 8787
  workerImage: prsridha/cerebro-kube:latest
workerMOP:
  checkpointPath: /data/cerebro_checkpoint_storage
  controllerDataPath: /data/cerebro_data_storage
  workerDataPath: /cerebro_data_storage_worker
  rcpport: 7777
  workerImage: prsridha/cerebro-kube:latest
