controller:
  volumes:
    configCapacity: 1Gi
    configMountPath: /data/cerebro_config_storage
    nodeHardwareInfo: /data/node_hardware_info
    checkpointCapacity: 20Gi
    checkpointMountPath: /data/cerebro_checkpoint_storage
    metricsCapacity: 5Gi
    metricsMountPath: /data/cerebro_metrics_storage
    dataCapacity: 70Gi
    dataMountPath: /data/cerebro_data_storage
    cerebroRepoHostPath: /home/ec2-user/cerebro-repo
    cerebroRepoMountPath: /cerebro-repo
    userRepoHostPath: /home/ec2-user/user-repo
    userRepoMountPath: /user-repo
    webappHostPath: /home/ec2-user/web-app
    webappMountPath: /webapp
  git:
    cerebroRepoURL: git@github.com:prsridha/cerebro-kube.git
    cerebroRepoBranch: demo
    gitSyncImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/git-sync:latest
    image: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  services:
    daskPort: 8786
    daskDashboardPort: 8787
    webappPort: 8080
    webappUIPort: 80
    jupyterPort: 8888
    jupyterNodePort: 30888
    tensorboardPort: 6006
    tensorboardNodePort: 30999
    webappNodePort: 30083
    webappUINodePort: 30080
creds:
  gitServer: github.com
  gitToken: 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
namespace: cerebro
cluster:
  name: cerebro-kube-small-1
  workerSpotInstance: false
  numWorkers: 3
  region: ca-central-1
  controllerInstance: t3.2xlarge
  workerInstances:
  - g4dn.12xlarge
  volumeSize: 200
  efsFileSystemIds:
    checkpointFsId: fs-032471efe14ba176c
    dataFsId: fs-00ef37fcba0716d36
    metricsFsId: fs-0fb25e08417609c0c
    configFsId: fs-08a0bee6f3df01ab7
  pemPath: /Users/pradsrid/Mine/Masters/Research/Cerebro/AWSCreds/cerebro-kube-kp.pem
  containerImageRegistery: 602401143452.dkr.ecr.ap-south-1.amazonaws.com
  networking:
    nodeLocalListenIP: 169.254.0.0
    prometheusNodePort: 30090
    lokiPort: 3100
  URLs:
    publicDNSName: ec2-15-223-49-97.ca-central-1.compute.amazonaws.com
workerETL:
  workerDataPath: /cerebro_data_storage_worker
  port: 8787
  percentETLCores: 50
  workerContainerPort: 8787
  workerImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
workerMOP:
  dataMountPath: /data/cerebro_data_storage
  workerDataPath: /cerebro_data_storage_worker
  rpcport: 7777
  workerImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
