controller:
  volumes:
    configCapacity: 500Mi
    configMountPath: /data/cerebro_config_storage
    checkpointCapacity: 20Gi
    checkpointMountPath: /data/cerebro_checkpoint_storage
    metricsCapacity: 5Gi
    metricsMountPath: /data/cerebro_metrics_storage
    dataCapacity: 50Gi
    dataMountPath: /data/cerebro_data_storage
    cerebroRepoHostPath: /home/ec2-user/cerebro-repo
    cerebroRepoMountPath: /cerebro-repo
    userRepoHostPath: /home/ec2-user/user-repo
    userRepoMountPath: /user-repo
  git:
    cerebroRepoURL: git@github.com:prsridha/cerebro-kube.git
    cerebroRepoBranch: feature/aws-gpu
    userRepoURL: git@github.com:prsridha/coco-mop.git
    gitSyncImage: 782408612084.dkr.ecr.us-west-1.amazonaws.com/git-sync:latest
    image: 782408612084.dkr.ecr.us-west-1.amazonaws.com/cerebro-kube:latest
  services:
    daskDashboardPort: 8787
    daskPort: 8786
    tensorboardPort: 6006
    jupyterPort: 8888
    jupyterUserPort: 9999
creds:
  gitServer: github.com
  gitToken: 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
namespace: cerebro
cluster:
  name: cerebro-kube-big-1
  workerSpot: true
  workers: 8
  region: us-west-1
  controllerInstance: t3.xlarge
  workerInstance: g4dn.8xlarge
  volumeSize: 200
  efsFileSystemIds:
    checkpointFsId: fs-0b7c52901116234b3
    dataFsId: fs-056096b5ae63c9629
    metricsFsId: fs-05f111d2860bf0b1d
    configFsId: fs-0393d773b2f9791d2
  pemPath: /Users/pradsrid/Mine/Masters/Research/Cerebro/AWSCreds/cerebro-kube-kp.pem
  containerImageRegistery: 602401143452.dkr.ecr.ap-south-1.amazonaws.com
  nodeLocalListenIP: 169.254.0.0
workerETL:
  workerDataPath: /cerebro_data_storage_worker
  port: 8787
  schedulerIP: 10.100.239.232
  workerContainerPort: 8787
  workerImage: 782408612084.dkr.ecr.us-west-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
workerMOP:
  dataMountPath: /data/cerebro_data_storage
  workerDataPath: /cerebro_data_storage_worker
  rcpport: 7777
  workerImage: 782408612084.dkr.ecr.us-west-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
