controller:
  volumes:
    cerebroRepoCapacity: 5Gi
    userRepoCapacity: 5Gi
    configCapacity: 5Gi
    configMountPath: /data/cerebro_config_storage
    nodeHardwareInfo: /data/node_hardware_info
    checkpointCapacity: 50Gi
    checkpointMountPath: /data/cerebro_checkpoint_storage
    metricsCapacity: 15Gi
    metricsMountPath: /data/cerebro_metrics_storage
    sharedDataCapacity: 100Gi
    nodeDataCapacity: 130Gi
    dataMountPath: /data/cerebro_data_storage
    cerebroRepoMountPath: /cerebro-repo
    userRepoMountPath: /user-repo
  git:
    cerebroRepoURL: git@github.com:prsridha/cerebro-kube.git
    cerebroRepoBranch: feature/stability-improvement
    gitSyncImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/git-sync:latest
    image: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  services:
    jupyterPort: 8888
    jupyterNodePort: 30888
    tensorboardPort: 6006
    tensorboardNodePort: 30999
creds:
  gitServer: github.com
  gitToken: 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
  jupyterTokenSting: projectcerebro
  csvPath: csvPath.csv
  pemPath: /Users/pradsrid/Mine/Masters/Research/Cerebro/AWSCreds/cerebro-kube-kp.pem
namespace: cerebro
cluster:
  name: cerebro-kube-small-1
  kubernetesVersion: 1.26
  workerSpotInstance: false
  numWorkers: 2
  numGPUs: 4
  region: ca-central-1
  controllerInstance: t3.2xlarge
  workerInstances:
  - g4dn.12xlarge
  volumeSize: 200
  efsFileSystemId: fs-0cb2d46de07e48d70
  networking:
    nodeLocalListenIP: 169.254.0.0
    prometheusNodePort: 30090
    grafanaNodePort: 30030
    lokiPort: 3100
    publicDNSName: ec2-15-222-236-155.ca-central-1.compute.amazonaws.com
worker:
  dataMountPath: /data/cerebro_data_storage
  workerDataPath: /cerebro_data_storage_worker
  rpcPort: 7777
  workerDataHostPath: /mnt/cerebro_data_storage_worker
webApp:
  mountPath: /data
  backendPort: 8083
  backendNodePort: 30083
  uiPort: 80
  uiNodePort: 30080
  repoURL: git@github.com:prsridha/cerebro-ui.git
  image: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-ui:latest
