controller:
  volumes:
    configCapacity: 1Gi
    configMountPath: /data/cerebro_config_storage
    nodeHardwareInfo: /data/node_hardware_info
    checkpointCapacity: 20Gi
    checkpointMountPath: /data/cerebro_checkpoint_storage
    metricsCapacity: 5Gi
    metricsMountPath: /data/cerebro_metrics_storage
    dataCapacity: 70Gi
    dataMountPath: /data/cerebro_data_storage
    cerebroRepoHostPath: /home/ec2-user/cerebro-repo
    cerebroRepoMountPath: /cerebro-repo
    userRepoHostPath: /home/ec2-user/user-repo
    userRepoMountPath: /user-repo
  git:
    cerebroRepoURL: git@github.com:prsridha/cerebro-kube.git
    cerebroRepoBranch: feature/ray-migration
    userRepoURL: git@github.com:prsridha/coco-mop.git
    userRepoBranch: feature/ray-migration
    gitSyncImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/git-sync:latest
    image: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  services:
    tensorboardPort: 6006
    jupyterPort: 8888
    jupyterUserPort: 9999
creds:
  gitServer: github.com
  gitToken: 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
namespace: cerebro
cluster:
  name: cerebro-kube-small-1
  workerSpot: false
  workers: 3
  region: ca-central-1
  controllerInstance: t3.2xlarge
  workerInstance:
  - g4dn.12xlarge
  volumeSize: 200
  efsFileSystemIds:
    checkpointFsId: fs-04412089570db5d96
    dataFsId: fs-044804b3c41081b95
    metricsFsId: fs-062d26f0709c9d6e7
    configFsId: fs-018f8caee6c4df3cf
  pemPath: /Users/pradsrid/Mine/Masters/Research/Cerebro/AWSCreds/cerebro-kube-kp.pem
  containerImageRegistery: 602401143452.dkr.ecr.ap-south-1.amazonaws.com
  nodeLocalListenIP: 169.254.0.0
workerETL:
  workerDataPath: /cerebro_data_storage_worker
  etlPort: 8083
  workerImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
workerMOP:
  dataMountPath: /data/cerebro_data_storage
  workerDataPath: /cerebro_data_storage_worker
  rcpport: 7777
  workerImage: 782408612084.dkr.ecr.ca-central-1.amazonaws.com/cerebro-kube:latest
  workerDataHostPath: /mnt/cerebro_data_storage_worker
