# Worker Service 
apiVersion: v1
kind: Service
metadata:
  name: cerebro-service-worker-{{ .Values.workerID }}
  namespace: {{ .Release.Namespace }}
  labels:
    type: cerebro-worker
spec:
  selector:
    app: cerebro-worker-{{ .Values.workerID }}
  ports:
  - name: "dask-port"
    protocol: "TCP"
    port: {{ .Values.worker.port }}
    targetPort: {{ .Values.worker.workerContainerPort }}
  - name: "rpc-port"
    protocol: "TCP"
    port: {{ .Values.worker.rcpport }}
    targetPort: {{ .Values.worker.rcpport }}
  type: LoadBalancer