# Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebro-worker-mop-{{ .Values.workerID }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: cerebro-worker-mop-{{ .Values.workerID }}
      type: cerebro-worker-mop
  replicas: 1
  template:
    metadata:
      labels:
        app: cerebro-worker-mop-{{.Values.workerID}}
        type: cerebro-worker-mop
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cerebro/nodename
                operator: In
                values:
                - node{{ .Values.workerID }}
      initContainers:
      - name: git-sync-cerebro
        image: {{ .Values.controller.git.gitSyncImage }}
        imagePullPolicy: Always
        volumeMounts:
        - name: cerebro-repo
          mountPath: {{ .Values.controller.volumes.cerebroRepoMountPath }}
        - name: git-secret
          mountPath: /etc/git-secret
        env:
        - name: GIT_SYNC_REPO
          value: {{ .Values.controller.git.cerebroRepoURL }}
        - name: GIT_SYNC_BRANCH
          value: {{ .Values.controller.git.cerebroRepoBranch }}
        - name: GIT_SYNC_ROOT
          value: {{ .Values.controller.volumes.cerebroRepoMountPath }}
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_SERVER
          value: {{ .Values.creds.gitServer }}
        securityContext:
          runAsUser: 0
      - name: git-sync-user-repo
        image: {{ .Values.controller.git.gitSyncImage }}
        imagePullPolicy: Always
        volumeMounts:
        - name: user-repo
          mountPath: {{ .Values.controller.volumes.userRepoMountPath }}
        - name: git-secret
          mountPath: /etc/git-secret
        env:
        - name: GIT_SYNC_REPO
          value: {{ .Values.controller.git.userRepoURL }}
        - name: GIT_SYNC_BRANCH
          value: main
        - name: GIT_SYNC_ROOT
          value: {{ .Values.controller.volumes.userRepoMountPath }}
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_SERVER
          value: {{ .Values.creds.gitServer }}
        securityContext:
          runAsUser: 0
      containers:
      - name: cerebro-worker-mop-{{ .Values.workerID }}-container
        image: {{ .Values.controller.git.image }}
        imagePullPolicy: Always
        command: [ "/bin/bash", "/cerebro-repo/cerebro-kube/init.sh"]
        workingDir: /cerebro-repo/cerebro-kube
        env:
        - name: WORKER_ID_SELF
          value: "{{ .Values.workerID }}"
        - name: POD_TYPE
          value: "mop"
        volumeMounts:
        - name: cerebro-repo
          mountPath: {{ .Values.controller.volumes.cerebroRepoMountPath }}
        - name: user-repo
          mountPath: {{ .Values.controller.volumes.userRepoMountPath }}
        - name: cerebro-data-storage-worker
          mountPath: {{ .Values.workerMOP.workerDataPath }}
        - name: cerebro-checkpoint-storage
          mountPath: {{ .Values.workerMOP.checkpointMountPath }}
        - name: cerebro-controller-storage
          mountPath: {{ .Values.controller.volumes.dataMountPath }}
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: user-repo
        hostPath:
          path: {{ .Values.controller.volumes.userRepoHostPath }}
          type: Directory
      - name: cerebro-repo
        hostPath:
          path: {{ .Values.controller.volumes.cerebroRepoHostPath }}
          type: Directory
      - name: cerebro-data-storage-worker
        hostPath:
          path: {{ .Values.workerMOP.workerDataHostPath}}
          type: DirectoryOrCreate
      - name: cerebro-checkpoint-storage
        persistentVolumeClaim:
          claimName: cerebro-checkpoint-pvc
      - name: cerebro-controller-storage
        persistentVolumeClaim:
          claimName: cerebro-data-pvc
      - name: git-secret
        secret:
          defaultMode: 256
          secretName: git-creds # your-ssh-key