# Worker StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cerebro-worker-mop
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: workermopsvc
  replicas: {{ .Values.cluster.numWorkers }}
  selector:
    matchLabels:
      app: cerebro-worker-mop
      type: cerebro-worker-mop
  template:
    metadata:
      labels:
        app: cerebro-worker-mop
      annotations:
        statefulset.kubernetes.io/pod-name: cerebro-worker-mop-$(POD_INDEX)
    spec:
      containers:
      - name: cerebro-worker-mop-container
        image: {{ .Values.controller.git.image }}
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "/cerebro-repo/cerebro-kube/init.sh"]
        workingDir: /cerebro-repo/cerebro-kube
        resources:
          limits:
            nvidia.com/gpu: {{ .Values.numGPU }}
        env:
        - name: WORKER_ID_SELF
          value: "$(POD_INDEX)"
        - name: POD_TYPE
          value: "mop"
        volumeMounts:
        - name: git-secret
          mountPath: /etc/git-secret
        - name: cerebro-repo
          mountPath: {{ .Values.controller.volumes.cerebroRepoMountPath }}
        - name: user-repo
          mountPath: {{ .Values.controller.volumes.userRepoMountPath }}
        - name: cerebro-data-storage-worker
          mountPath: {{ .Values.workerMOP.workerDataPath }}
        - name: cerebro-checkpoint-storage
          mountPath: {{ .Values.controller.volumes.checkpointMountPath }}
        - name: cerebro-controller-storage
          mountPath: {{ .Values.controller.volumes.dataMountPath }}
        - name: cerebro-metrics-storage
          mountPath: {{ .Values.controller.volumes.metricsMountPath }}
      volumes:
      - name: user-repo
        hostPath:
          path: {{ .Values.controller.volumes.userRepoHostPath }}
          type: Directory
      - name: cerebro-repo
        hostPath:
          path: {{ .Values.controller.volumes.cerebroRepoHostPath }}
          type: Directory
      - name: cerebro-data-storage-worker
        hostPath:
          path: {{ .Values.workerMOP.workerDataHostPath}}
          type: DirectoryOrCreate
      - name: cerebro-checkpoint-storage
        persistentVolumeClaim:
          claimName: cerebro-checkpoint-pvc
      - name: cerebro-controller-storage
        persistentVolumeClaim:
          claimName: cerebro-data-pvc
      - name: cerebro-metrics-storage
        persistentVolumeClaim:
          claimName: cerebro-metrics-pvc
      - name: git-secret
        secret:
          defaultMode: 256
          secretName: git-creds # your-ssh-key