apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cerebro-kube-big-1
  region: us-west-1
availabilityZones: ["us-west-1b", "us-west-1c"]
managedNodeGroups:
- name: ng-controller
  labels:
    role: controller
  instanceType: t3.xlarge
  desiredCapacity: 1
  volumeSize: 200
  ssh:
    allow: true
    publicKeyName: cerebro-kube-kp
- name: ng-worker
  labels:
    role: worker
  instanceType: g4dn.8xlarge
  desiredCapacity: 8
  volumeSize: 200
  ami: ami-0d2498f26d22a3857
  availabilityZones:
  - us-west-1b
  - us-west-1c
  spot: true
  ssh:
    allow: true
    publicKeyName: cerebro-kube-kp
  overrideBootstrapCommand: |
    #!/bin/bash

    /etc/eks/bootstrap.sh cerebro-kube-big-1 --container-runtime containerd
