apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: {{ name }}
  region: {{ region }}
availabilityZones: ["ca-central-1a", "ca-central-1b"]
managedNodeGroups:
- name: ng-controller
  labels:
    role: controller
  instanceType: {{ controller.instanceType }}
  desiredCapacity: 1
  volumeSize: {{ volumeSize }}
  ssh:
    allow: true
    publicKeyName: cerebro-kube-kp
- name: ng-worker
  labels:
    role: worker
  instanceTypes: {{ worker.instanceType }}
  desiredCapacity: {{ desiredCapacity }}
  volumeSize: {{ volumeSize }}
  ami: ami-09e225cf6c5c13915
  availabilityZones:
  - ca-central-1a
  - ca-central-1b
  spot: {{ workerSpot }}
  ssh:
    allow: true
    publicKeyName: cerebro-kube-kp
  overrideBootstrapCommand: |
    #!/bin/bash

    /etc/eks/bootstrap.sh {{ name }} --container-runtime containerd
