apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: {{ name }}
  region: {{ region }}
availabilityZones: ["us-west-1b", "us-west-1c"]
managedNodeGroups:
- name: ng-controller
  labels:
    role: controller
  instanceType: {{ controller.instanceType }}
  desiredCapacity: 1
  volumeSize: {{ volumeSize }}
  ssh:
    allow: true
    publicKeyName: cerebro-kube-kp
- name: ng-worker
  labels:
    role: worker
  instanceType: {{ worker.instanceType }}
  desiredCapacity: {{ desiredCapacity }}
  volumeSize: {{ volumeSize }}
  ami: ami-0d2498f26d22a3857
  availabilityZones:
  - us-west-1b
  - us-west-1c
  spot: {{ workerSpot }}
  ssh:
    allow: true
    publicKeyName: cerebro-kube-kp
  overrideBootstrapCommand: |
    #!/bin/bash

    /etc/eks/bootstrap.sh {{ name }} --container-runtime containerd
