apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cerebro-kube-2
  region: ap-south-1
managedNodeGroups:
- name: ng-controller
  labels:
    role: controller
  instanceType: t3.medium
  desiredCapacity: 1
  volumeSize: 80
  spot: true
  ssh:
    allow: true
    publicKeyName: cerebro-kube-kp
    enableSsm: true
- name: ng-worker
  labels:
    role: worker
  instanceType: t3.large
  desiredCapacity: 4
  volumeSize: 80
  spot: true
  ssh:
    allow: true
    publicKeyName: cerebro-kube-kp
    enableSsm: true
