apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cerebro-kube-1
  region: ap-south-1
availabilityZones: ["ap-south-1a", "ap-south-1b"]
managedNodeGroups:
- name: ng-controller
  labels:
    role: controller
  instanceType: t3.large
  desiredCapacity: 1
  volumeSize: 80
  ssh:
    allow: true
    publicKeyName: cerebro-kube-kp
- name: ng-worker1
  labels:
    role: worker
  instanceType: p2.xlarge
  desiredCapacity: 4
  volumeSize: 80
  ami: ami-0afd3b7820ccf34a0
  availabilityZones: ["ap-south-1a", "ap-south-1b"]
  spot: true
  ssh:
    allow: true
    publicKeyName: cerebro-kube-kp
  overrideBootstrapCommand: |
    #!/bin/bash
    /etc/eks/bootstrap.sh cerebro-kube-1 --container-runtime containerd