kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: allow-all
rules:
- apiGroups: [""]
  resources: ["pods","services","namespaces","deployments","jobs"] 
  verbs: ["update", "get", "patch", "list", "watch"]