kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: cerebro
  name: pods-list
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: cerebro
  name: pods-copy
rules:
- apiGroups: [""]
  resources: ["pods/exec"] 
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
metadata:
  namespace: cerebro
  name: pods-list-bind
subjects:
- kind: ServiceAccount
  name: default # Name is case sensitive
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
metadata:
  namespace: cerebro
  name: pods-copy-bind
subjects:
- kind: ServiceAccount
  name: default # Name is case sensitive
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: pods-copy
  apiGroup: ""