# Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebro-worker-{{ .Values.workerID }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: cerebro-worker-{{ .Values.workerID }}
      type: cerebro-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: cerebro-worker-{{.Values.workerID}}
        type: cerebro-worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cerebro/nodename
                operator: In
                values:
                - node{{ add .Values.workerID 1}}
      initContainers:
      - name: git-sync-user-repo
        image: {{ .Values.controller.gitSyncImage }}
        imagePullPolicy: Always
        volumeMounts:
        - name: user-repo
          mountPath: {{ .Values.controller.userRepoMountPath }}
        - name: git-secret
          mountPath: /etc/git-secret
        env:
        - name: GIT_SYNC_REPO
          value: {{ .Values.controller.userRepoURL }}
        - name: GIT_SYNC_BRANCH
          value: main
        - name: GIT_SYNC_ROOT
          value: {{ .Values.controller.userRepoMountPath }}
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_SERVER
          value: {{ .Values.creds.gitServer }}
        securityContext:
          runAsUser: 0
      containers:
      - name: cerebro-worker-{{ .Values.workerID }}-container
        image: {{ .Values.worker.workerImage }}
        imagePullPolicy: Always
        env:
        - name: WORKER_ID_SELF
          value: "{{ .Values.workerID }}"
        volumeMounts:
        - name: user-repo
          mountPath: {{ .Values.controller.userRepoMountPath }}
        - name: cerebro-hyperparamter-storage
          mountPath: {{ .Values.worker.hyperparameterMountPath }}
        - name: cerebro-data-storage-worker
          mountPath: {{ .Values.worker.dataMountPath }}
        - name: cerebro-checkpoint-storage
          mountPath: {{ .Values.worker.checkpointMountPath }}
        - name: cerebro-controller-storage
          mountPath: {{ .Values.worker.controllerDataMountPath }}
        ports:
        - containerPort: {{ .Values.worker.workerContainerPort }}
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: user-repo
        hostPath:
          path: {{ .Values.controller.userRepoHostPath }}
          type: Directory
      - name: cerebro-hyperparamter-storage
        configMap:
          name: hyperparameter-properties
      - name: cerebro-data-storage-worker
        hostPath:
          path: /mnt/cerebro_data_storage_worker
          type: DirectoryOrCreate
      - name: cerebro-checkpoint-storage
        persistentVolumeClaim:
          claimName: cerebro-checkpoint-pvc
      - name: cerebro-controller-storage
        persistentVolumeClaim:
          claimName: cerebro-data-pvc
      - name: git-secret
        secret:
          defaultMode: 256
          secretName: git-creds # your-ssh-key