# Controller Persistent Volume Claim

# Checkpoint pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-checkpoint-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.controller.volumes.checkpointCapacity }}
  selector: 
    matchLabels:
      name: cerebro-checkpoint-pv
---
# Config pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.controller.volumes.configCapacity }}
  selector: 
    matchLabels:
      name: cerebro-config-pv
---
# Data pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.controller.volumes.dataCapacity }}
  selector: 
    matchLabels:
      name: cerebro-data-pv