# Controller Service 
apiVersion: v1
kind: Service
metadata:
  name: cerebro-controller-service
  namespace: {{ .Release.Namespace }}
  labels:
    type: cerebro-controller-svc
    serviceApp: ray
spec:
  selector:
    app: cerebro-controller
  ports:
  - protocol: "TCP"
    port: {{ .Values.controller.services.rayPort }}
    targetPort: {{ .Values.controller.services.rayPort }}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: cerebro-controller-port-forward-jupyter
  namespace: {{ .Release.Namespace }}
  labels:
    type: cerebro-controller-svc
    serviceApp: jupyter
spec:
  selector:
    app: cerebro-controller
  ports:
    - port: {{ .Values.controller.services.jupyterPort }}
      targetPort: {{ .Values.controller.services.jupyterPort }}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: cerebro-controller-port-forward-tnsrbrd
  namespace: {{ .Release.Namespace }}
  labels:
    type: cerebro-controller-svc
    serviceApp: tensorboard
spec:
  selector:
    app: cerebro-controller
  ports:
    - port: {{ .Values.controller.services.tensorboardPort }}
      targetPort: {{ .Values.controller.services.tensorboardPort }}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: cerebro-controller-port-forward-ray
  namespace: {{ .Release.Namespace }}
  labels:
    type: cerebro-controller-svc
    serviceApp: ray
spec:
  selector:
    app: cerebro-controller
  ports:
    - port: {{ .Values.controller.services.rayDashboardPort }}
      targetPort: {{ .Values.controller.services.rayDashboardPort }}
  type: NodePort