# Controller Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebro-controller
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: cerebro-controller
      type: cerebro-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: cerebro-controller
        type: cerebro-controller
    spec:
      hostname: cerebro-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - controller
      serviceAccountName: s3-eks-sa
      initContainers:
      - name: git-sync-cerebro
        image: {{ .Values.controller.git.gitSyncImage }}
        imagePullPolicy: Always
        volumeMounts:
        - name: cerebro-repo
          mountPath: {{ .Values.controller.volumes.cerebroRepoMountPath }}
        - name: git-secret
          mountPath: /etc/git-secret
        env:
        - name: GIT_SYNC_REPO
          value: {{ .Values.controller.git.cerebroRepoURL }}
        - name: GIT_SYNC_BRANCH
          value: {{ .Values.controller.git.cerebroRepoBranch }}
        - name: GIT_SYNC_ROOT
          value: {{ .Values.controller.volumes.cerebroRepoMountPath }}
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_SYNC_SERVER
          value: {{ .Values.creds.gitServer }}
        securityContext:
          runAsUser: 0
      containers:
      - name: cerebro-controller-container
        image: {{ .Values.controller.git.image }}
        imagePullPolicy: Always
        command: [ "/bin/bash", "/cerebro-repo/cerebro-kube/init.sh"]
        workingDir: /cerebro-repo/cerebro-kube
        env:
        - name: POD_TYPE
          value: "controller"
        - name: RPC_PORT
          value: "{{ .Values.worker.rpcPort }}"
        - name: ML_METRICS_LOGDIR
          value: {{ .Values.controller.volumes.metricsMountPath }}
        volumeMounts:
        - name: git-secret
          mountPath: /etc/git-secret
        - name: cerebro-repo
          mountPath: {{ .Values.controller.volumes.cerebroRepoMountPath }}
        - name: user-repo
          mountPath: {{ .Values.controller.volumes.userRepoMountPath }}
        - name: cerebro-checkpoint-storage
          mountPath: {{ .Values.controller.volumes.checkpointMountPath }}
        - name: cerebro-config-storage
          mountPath: {{ .Values.controller.volumes.configMountPath }}
        - name: cerebro-data-storage
          mountPath: {{ .Values.controller.volumes.dataMountPath }}
        - name: cerebro-metrics-storage
          mountPath: {{ .Values.controller.volumes.metricsMountPath }}
        ports:
        - containerPort: {{ .Values.controller.services.jupyterPort }}
          name: jupyter-port
        - containerPort: {{ .Values.controller.services.tensorboardPort }}
          name: tnsrbrd-port
      volumes:
      - name: cerebro-repo
        persistentVolumeClaim:
          claimName: cerebro-repo-pvc
      - name: user-repo
        persistentVolumeClaim:
          claimName: user-repo-pvc
      - name: cerebro-checkpoint-storage
        persistentVolumeClaim:
          claimName: cerebro-checkpoint-pvc
      - name: cerebro-config-storage
        persistentVolumeClaim:
          claimName: cerebro-config-pvc
      - name: cerebro-metrics-storage
        persistentVolumeClaim:
          claimName: cerebro-metrics-pvc
      - name: cerebro-data-storage
        persistentVolumeClaim:
          claimName: cerebro-data-pvc
      - name: git-secret
        secret:
          defaultMode: 256
          secretName: git-creds