# Controller Persistent Volume

# Checkpoint Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cerebro-checkpoint-pv
  labels:
    name: cerebro-checkpoint-pv
spec:
  capacity:
    storage: {{ .Values.controller.volumes.checkpointCapacity }}
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.cluster.efsFileSystemID }}
---
# Data Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cerebro-data-pv
  labels:
    name: cerebro-data-pv
spec:
  capacity:
    storage: {{ .Values.controller.volumes.dataCapacity }}
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.cluster.efsFileSystemID }}
---
# Config Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cerebro-config-pv
  labels:
    name: cerebro-config-pv
spec:
  capacity:
    storage: {{ .Values.controller.volumes.configCapacity }}
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.cluster.efsFileSystemID }}
---
# Metrics Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cerebro-metrics-pv
  labels:
    name: cerebro-metrics-pv
spec:
  capacity:
    storage: {{ .Values.controller.volumes.metricsCapacity }}
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.cluster.efsFileSystemID }}