# Controller Persistent Volume Claim

# Checkpoint pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-checkpoint-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.controller.volumes.checkpointCapacity }}
---
# Config pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.controller.volumes.configCapacity }}
---
# Data pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.controller.volumes.dataCapacity }}
---
# Data pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-metrics-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: {{ .Values.controller.volumes.metricsCapacity }}