# Webapp Service 
apiVersion: v1
kind: Service
metadata:
  name: cerebro-webapp-service
  namespace: {{ .Release.Namespace }}
  labels:
    type: cerebro-webapp-svc
    serviceApp: webapp
spec:
  selector:
    app: cerebro-webapp
  ports:
  - protocol: "TCP"
    port: {{ .Values.controller.services.webappPort }}
    targetPort: {{ .Values.controller.services.webappPort }}
    nodePort: {{ .Values.controller.services.webappNodePort }}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: cerebro-webapp-ui
  namespace: {{ .Release.Namespace }}
  labels:
    type: cerebro-webapp-ui
    serviceApp: webapp
spec:
  selector:
    app: cerebro-webapp
  ports:
    - port: {{ .Values.controller.services.webappUIPort }}
      targetPort: {{ .Values.controller.services.webappUIPort }}
      nodePort: {{ .Values.controller.services.webappUINodePort}}
  type: NodePort